---
name: MegaLinter
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

env:
  MEGALINTER_CONFIG: /github/workspace/build-tools/mega-linter.yml

jobs:
  megalinter:
    name: megalint
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]')}}
    permissions:
      # Needed for Code scanning upload
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 7

      - name: Run MegaLinter
        id: ml
        uses: oxsecurity/megalinter@146333030da68e2e58c6ff826633824fabe01eaf # v8.5.0

      - name: Archive production artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports

      - name: Upload Megalint Sarif Report
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0 # v3.28.9
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
