name: Release

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Node.js v22 is not available yet. Use a stable version like v16 or v14

      - name: Install dependencies
        run: |
          npm ci

      - name: Run semantic-release
        run: |
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Ensure the secret 'MY_GITHUB_TOKEN' is added in your repository secrets
