name: Release

on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user for commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Run standard-version
        run: npm run release

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout the PR source branch
        run: git checkout ${{ github.head_ref }}

      - name: Commit version bump and changelog
        run: |
          git add .
          git status  # Check if there are any changes to commit
          git commit -m "chore(release): ${GITHUB_SHA}" || echo "No changes to commit"
          git push origin ${{ github.head_ref }}

      # Optional: Create Git tag
      - name: Create Git tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
