---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commit:
    uses: ./.github/workflows/commit.yaml
  lint:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/lint.yml
